import { PropsWithChildren } from "react";
import "./globals.css";
import { Nunito } from "next/font/google";
import { cn } from "~/lib/cn";
import Toolbar from "~/components/toolbar";

const inter = Nunito({ subsets: ["latin"] });

type RootLayoutProps = PropsWithChildren<unknown>;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "container max-w-[65ch] p-7 bg-slate-50 md:p-0"
        )}
      >
        <Toolbar />
        {children}
      </body>
    </html>
  );
}
